/**
 * The reviewed vocabulary list: reading it, and writing it back without losing
 * a single decision the owner made.
 *
 * WHY A DECISION AND NOT JUST A DELETION. The list is candidates drawn from the
 * published books, and three of them turn out to be different things:
 *
 *   a real word the dictionary lacked      «ئەلەيھى»  → admit it
 *   a misspelling the books repeat         «رسول»     → do NOT admit it, and
 *                                                       teach the checker that
 *                                                       «رەسۇل» is what was meant
 *   something that is not a word at all    a fragment → reject it, silently
 *
 * Deleting a line only ever expressed the third. A correction is worth far more
 * than a deletion: it keeps the wrong form OUT of the dictionary, puts the right
 * form IN, and adds the pair to the correction table so anyone who types the
 * wrong form is offered the right one first. One line of review does all three.
 *
 * DECISIONS SURVIVE REGENERATION. Re-running the build must never quietly throw
 * away an afternoon of reading. Every line already in the file is carried
 * forward with its decision attached, including rejections — which is why a
 * rejection is written as «-» rather than expressed by deleting the line.
 * Deleting still works for a one-off, but the next scan will offer the word
 * again; «-» is remembered.
 */
import { readFileSync, existsSync } from "node:fs";

/**
 * `word  times  books` with an optional decision, where BOTH the word and the
 * correction may contain spaces.
 *
 * That last part is not theoretical. A reviewer reading real text finds forms
 * the corpus joined that Uyghur writes apart — «ۋەياكى» is properly «ۋە ياكى» —
 * and writing the correction as two words is the right answer. An earlier
 * version required a single token on each side and silently skipped those
 * lines, which is the worst possible failure here: the reviewer's judgement
 * disappears and nothing says so.
 *
 * The counts anchor the parse. `(.+?)` is lazy, so it stops at the first place
 * two numbers follow, which is exactly where the word ends however many spaces
 * it contains.
 */
const WITH_COUNTS = /^(.+?)\s+(\d+)\s+(\d+)\s*(?:=\s*(.+?)|(-))?\s*$/;
/** The same without them, so a hand-typed line does not have to carry numbers. */
const WITHOUT_COUNTS = /^(.+?)\s*(?:=\s*(.+?)|\s(-))\s*$/;

/**
 * One entry, however the owner wrote it.
 *
 * Tabs and spaces are both accepted, and so is a line with the counts stripped
 * off. Someone editing 2,000 lines by hand should not have to preserve a column
 * layout, and a format that punishes them for it will not get used.
 */
export function parseVocabulary(text) {
  const entries = [];
  for (const raw of text.split("\n")) {
    const line = raw.replace(/\r$/, "").trim();
    if (!line || line.startsWith("#")) continue;

    const counted = WITH_COUNTS.exec(line);
    if (counted) {
      const [, word, total, books, correction, rejected] = counted;
      entries.push({
        word: word.trim(),
        total: Number(total),
        books: Number(books),
        decision: correction ? "corrected" : rejected ? "rejected" : "admitted",
        correction: correction ? correction.trim() : null,
      });
      continue;
    }

    const bare = WITHOUT_COUNTS.exec(line);
    if (bare) {
      const [, word, correction, rejected] = bare;
      entries.push({
        word: word.trim(),
        total: 0,
        books: 0,
        decision: correction ? "corrected" : rejected ? "rejected" : "admitted",
        correction: correction ? correction.trim() : null,
      });
      continue;
    }

    // A plain word on its own, with nothing else on the line.
    entries.push({ word: line, total: 0, books: 0, decision: "admitted", correction: null });
  }
  return entries;
}

export function readVocabulary(path) {
  if (!existsSync(path)) return [];
  return parseVocabulary(readFileSync(path, "utf-8"));
}

const HEADER = `# كىتابخانىدىكى كىتابلاردا بار، ئەمما لۇغەتتە يوق سۆزلەر.
#
# بۇ تىزىملىكنى ئوقۇپ چىقىڭ. ھەر بىر قۇرغا ئۈچ خىل قارار بېرەلەيسىز:
#
#   سۆز    5   3            ← توغرا سۆز. لۇغەتكە قوشۇلىدۇ. (ھېچنېمە قىلمىسىڭىز شۇ)
#   سۆز    5   3   = توغرىسى ← خاتا يېزىلغان. لۇغەتكە قوشۇلمايدۇ، ۋە بۇنى
#                              يازغان كىشىگە «توغرىسى» تەۋسىيە قىلىنىدۇ.
#   سۆز    5   3   -         ← سۆز ئەمەس. چەتكە قېقىلىدۇ ۋە قايتا سورالمايدۇ.
#
# «=» بەلگىسى ئەڭ پايدىلىقى: خاتا شەكىلنى لۇغەتتىن چەتتە قالدۇرىدۇ، توغرا
# شەكىلنى لۇغەتكە كىرگۈزىدۇ، ھەمدە ئىككىسىنى تۈزىتىش جەدۋىلىگە قوشىدۇ.
#
# قۇرنى ئۆچۈرۈۋەتسىڭىزمۇ بولىدۇ، ئەمما كېيىنكى قېتىم قايتا سورىلىدۇ — «-»
# بولسا ئەستە تۇتۇلىدۇ. سىزنىڭ قارارلىرىڭىز قايتا قۇرغاندىمۇ ساقلىنىدۇ.
#
# Generated by scripts/build-vocabulary.mjs. Columns: word, occurrences, books.`;

/** Write the list back, decisions and all, with the widest column padded. */
export function formatVocabulary(entries, meta) {
  const width = Math.max(...entries.map((entry) => entry.word.length), 8);
  const lines = entries.map((entry) => {
    const head = `${entry.word.padEnd(width)}\t${entry.total}\t${entry.books}`;
    if (entry.decision === "corrected") return `${head}\t= ${entry.correction}`;
    if (entry.decision === "rejected") return `${head}\t-`;
    return head;
  });
  return `${HEADER}\n# ${meta}\n${lines.join("\n")}\n`;
}
