/**
 * The reviewed vocabulary list: reading it, and writing it back without losing
 * a single decision the owner made.
 *
 * WHY A DECISION AND NOT JUST A DELETION. The list is candidates drawn from the
 * published books, and three of them turn out to be different things:
 *
 *   a real word the dictionary lacked      «ئەلەيھى»  → admit it
 *   a misspelling the books repeat         «رسول»     → do NOT admit it, and
 *                                                       teach the checker that
 *                                                       «رەسۇل» is what was meant
 *   something that is not a word at all    a fragment → reject it, silently
 *
 * Deleting a line only ever expressed the third. A correction is worth far more
 * than a deletion: it keeps the wrong form OUT of the dictionary, puts the right
 * form IN, and adds the pair to the correction table so anyone who types the
 * wrong form is offered the right one first. One line of review does all three.
 *
 * DECISIONS SURVIVE REGENERATION. Re-running the build must never quietly throw
 * away an afternoon of reading. Every line already in the file is carried
 * forward with its decision attached, including rejections — which is why a
 * rejection is written as «-» rather than expressed by deleting the line.
 * Deleting still works for a one-off, but the next scan will offer the word
 * again; «-» is remembered.
 */
import { readFileSync, existsSync } from "node:fs";

/** `word = correction`, with any amount of space, and the counts optional. */
const CORRECTED = /^(\S+)(?:\s+(\d+)\s+(\d+))?\s*=\s*(\S+)\s*$/;
/** `word - ` — offered, read, and turned down. */
const REJECTED = /^(\S+)(?:\s+(\d+)\s+(\d+))?\s*-\s*$/;
/** `word  times  books` — admitted, the default. */
const ADMITTED = /^(\S+)(?:\s+(\d+)\s+(\d+))?\s*$/;

/**
 * One entry, however the owner wrote it.
 *
 * Tabs and spaces are both accepted, and so is a line with the counts stripped
 * off. Someone editing 2,000 lines by hand should not have to preserve a column
 * layout, and a format that punishes them for it will not get used.
 */
export function parseVocabulary(text) {
  const entries = [];
  for (const raw of text.split("\n")) {
    const line = raw.replace(/\r$/, "").trim();
    if (!line || line.startsWith("#")) continue;

    let match = CORRECTED.exec(line);
    if (match) {
      entries.push({
        word: match[1],
        total: Number(match[2] ?? 0),
        books: Number(match[3] ?? 0),
        decision: "corrected",
        correction: match[4],
      });
      continue;
    }
    match = REJECTED.exec(line);
    if (match) {
      entries.push({
        word: match[1],
        total: Number(match[2] ?? 0),
        books: Number(match[3] ?? 0),
        decision: "rejected",
        correction: null,
      });
      continue;
    }
    match = ADMITTED.exec(line);
    if (match) {
      entries.push({
        word: match[1],
        total: Number(match[2] ?? 0),
        books: Number(match[3] ?? 0),
        decision: "admitted",
        correction: null,
      });
    }
  }
  return entries;
}

export function readVocabulary(path) {
  if (!existsSync(path)) return [];
  return parseVocabulary(readFileSync(path, "utf-8"));
}

const HEADER = `# كىتابخانىدىكى كىتابلاردا بار، ئەمما لۇغەتتە يوق سۆزلەر.
#
# بۇ تىزىملىكنى ئوقۇپ چىقىڭ. ھەر بىر قۇرغا ئۈچ خىل قارار بېرەلەيسىز:
#
#   سۆز    5   3            ← توغرا سۆز. لۇغەتكە قوشۇلىدۇ. (ھېچنېمە قىلمىسىڭىز شۇ)
#   سۆز    5   3   = توغرىسى ← خاتا يېزىلغان. لۇغەتكە قوشۇلمايدۇ، ۋە بۇنى
#                              يازغان كىشىگە «توغرىسى» تەۋسىيە قىلىنىدۇ.
#   سۆز    5   3   -         ← سۆز ئەمەس. چەتكە قېقىلىدۇ ۋە قايتا سورالمايدۇ.
#
# «=» بەلگىسى ئەڭ پايدىلىقى: خاتا شەكىلنى لۇغەتتىن چەتتە قالدۇرىدۇ، توغرا
# شەكىلنى لۇغەتكە كىرگۈزىدۇ، ھەمدە ئىككىسىنى تۈزىتىش جەدۋىلىگە قوشىدۇ.
#
# قۇرنى ئۆچۈرۈۋەتسىڭىزمۇ بولىدۇ، ئەمما كېيىنكى قېتىم قايتا سورىلىدۇ — «-»
# بولسا ئەستە تۇتۇلىدۇ. سىزنىڭ قارارلىرىڭىز قايتا قۇرغاندىمۇ ساقلىنىدۇ.
#
# Generated by scripts/build-vocabulary.mjs. Columns: word, occurrences, books.`;

/** Write the list back, decisions and all, with the widest column padded. */
export function formatVocabulary(entries, meta) {
  const width = Math.max(...entries.map((entry) => entry.word.length), 8);
  const lines = entries.map((entry) => {
    const head = `${entry.word.padEnd(width)}\t${entry.total}\t${entry.books}`;
    if (entry.decision === "corrected") return `${head}\t= ${entry.correction}`;
    if (entry.decision === "rejected") return `${head}\t-`;
    return head;
  });
  return `${HEADER}\n# ${meta}\n${lines.join("\n")}\n`;
}
